### ISSUE TITLE
Version 1.1 Release Errors

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#1043]
There are two urgent issues that we have to solve ASAP:

1. Read the Docs builds are timing out (so the latest documentation hasn't built yet)
2. ~Miniconda is erroring on AppVeyor for the master branch and release tag~

The RTD problem is related to a time out, though the docs built locally on my machine just fine, so we'll have to see if we can find an alternate fix for it. 

The AppVeyor issues may be temporary, but we should restart the builds once it's fixed.

**Comment by rebeccabilbro** [comment]
@bbengfort copy that &mdash; rerunning the incomplete AppVeyor builds now to see if the miniconda timeout issue is resolved. As for the RTD timeout, I suspect this may be due to the new plots being generated from the quick methods via plot directive (probably a few of the longer-running ones like pcoords). If we want to do a quick hotfix, I can do a quick PR to (A) swap those out with faster versions (e.g. `fast=True` for pcoords, smaller/toy datasets for tsne, umap, etc) or (B) for the slower images, pre-build with .py files and swap the dynamic plot directives with static images. Let me know if you have any preference between A and B or if you have another suggestion you think we could explore!

**Comment by rebeccabilbro** [comment]
Update: there appears to be something wrong with the miniconda image on AppVeyor

```bash
    Traceback (most recent call last):
      File "C:\Miniconda36-x64\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
        if spec.can_handle():
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\main.py", line 75, in load
        return loader.get_single_data()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\composer.py", line 56, in get_single_node
        if not self.check_event(StreamEndEvent):
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\parser.py", line 116, in check_event
        self.current_event = self.state()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\parser.py", line 194, in parse_document_start
        self.peek_token().start_mark)
    ruamel_yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
      in "<unicode string>", line 9, column 1:
        pytest>=4.2.0, !=4.6.0
        ^
Command exited with code 1
```

**Comment by rebeccabilbro** [comment]
Part # 2 has been resolved 🎉; see #1045

**Comment by rebeccabilbro** [comment]
Looks like Part # 1 is now resolved as well! https://www.scikit-yb.org/en/latest/index.html

**Comment by bbengfort** [comment]
Thanks for checking on this! Glad it's sorted.
