### ISSUE TITLE
ROCAUC.score() raises ValueError: Found input variables with inconsistent numbers of samples

### ISSUE THREAD

**Issue by pdeziel** [DistrictDataLabs/yellowbrick#1149]
**Describe the bug**

Fitting a LinearSVC model on a binary class dataset and calling the ROCAUC score() function causes an unexpected error to be raised from sklearn. If the binary=True parameter is passed into ROCAUC, the error goes away.

```ValueError: Found input variables with inconsistent numbers of samples: [4, 2]```

**To Reproduce**

```python
import numpy as np
from sklearn.svm import LinearSVC
from yellowbrick.classifier import ROCAUC

X = np.array([1, 2]).reshape(-1, 1)
y = np.array([0, 1])
model = LinearSVC()
visualizer = ROCAUC(model)
visualizer.fit(X, y)
visualizer.score(X, y)
```

**Expected behavior**

Yellowbrick should raise a more meaningful error if the binary=True parameter is required to score ROCAUC on binary class datasets.

**Traceback**

```
Traceback (most recent call last):
  File "visualizer.py", line 9, in <module>
    visualizer.score(X, y)
  File "C:\Users\DezielPa\conda\yellowbrick\yellowbrick\classifier\rocauc.py", line 330, in score
    self._score_micro_average(y, y_pred, classes, n_classes)
  File "C:\Users\DezielPa\conda\yellowbrick\yellowbrick\classifier\rocauc.py", line 486, in _score_micro_average
    self.fpr[MICRO], self.tpr[MICRO], _ = roc_curve(y.ravel(), y_pred.ravel())
  File "C:\Users\DezielPa\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 73, in inner_f
    return f(**kwargs)
  File "C:\Users\DezielPa\Anaconda3\lib\site-packages\sklearn\metrics\_ranking.py", line 776, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "C:\Users\DezielPa\Anaconda3\lib\site-packages\sklearn\metrics\_ranking.py", line 541, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "C:\Users\DezielPa\Anaconda3\lib\site-packages\sklearn\utils\validation.py", line 257, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [4, 2]
```

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Enterprise
 - Python 3.7.6
 - Yellowbrick Version 1.2.1

**Additional context**

sklearn version 0.23.0

**Comment by rebeccabilbro** [comment]
Thank you @pdeziel for noting this bug (and for your recent PR #1148!). 

My guess is we should take another look at the check we're doing [here](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier/rocauc.py#L262-L268) since we seem to be missing an edge case. Maybe we can take a look together on Wednesday and open a PR?
