### ISSUE TITLE
Documentation Exceptions

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#1188]
**Describe the bug**

There are two `.. plot::` directive bugs that are causing images to not be built in the documentation, their tracebacks are below.

**To Reproduce**

TODO: fill in this section with the code from the plot directives.

**Dataset**

See plot directives for internal YB datasets used. 

**Expected behavior**

The docs should build without exception and all plot directive images should be shown.

**Traceback**

Exception 1:

```
/github/workspace/docs/api/model_selection/learning_curve.rst:99: WARNING: Exception occurred in plotting learning_curve-3
 from /github/workspace/docs/api/model_selection/learning_curve.rst:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 483, in run_code
    exec(code, ns)
  File "<string>", line 13, in <module>
  File "/github/workspace/yellowbrick/model_selection/learning_curve.py", line 249, in fit
    curve = sk_learning_curve(self.estimator, X, y, **sklc_kwargs)
  File "/usr/local/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 1412, in learning_curve
    results = parallel(delayed(_fit_and_score)(
  File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 966, in __call__
    n_jobs = self._initialize_backend()
  File "/usr/local/lib/python3.8/site-packages/joblib/parallel.py", line 733, in _initialize_backend
    n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,
  File "/usr/local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 489, in configure
    n_jobs = self.effective_n_jobs(n_jobs)
  File "/usr/local/lib/python3.8/site-packages/joblib/_parallel_backends.py", line 525, in effective_n_jobs
    elif n_jobs < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
```

Exception 2: 

```
/github/workspace/docs/api/text/umap_vis.rst:141: WARNING: Exception occurred in plotting umap_vis-1
 from /github/workspace/docs/api/text/umap_vis.rst:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/matplotlib/sphinxext/plot_directive.py", line 483, in run_code
    exec(code, ns)
  File "<string>", line 17, in <module>
  File "/github/workspace/yellowbrick/text/umap_vis.py", line 116, in umap
    visualizer = UMAPVisualizer(
  File "/github/workspace/yellowbrick/text/umap_vis.py", line 210, in __init__
    raise YellowbrickValueError(
yellowbrick.exceptions.YellowbrickValueError: umap package doesn't seem to be installed.Please install UMAP via: pip install umap-learn
```

**Desktop (please complete the following information):**
 - OS: ubuntu-latest
 - Python Version 3.9
 - Yellowbrick Version: branch develop

**Comment by bbengfort** [comment]
RE #1187
