### ISSUE TITLE
Attempting to download datasets gives 403

### ISSUE THREAD

**Issue by exp-ouroborous** [DistrictDataLabs/yellowbrick#1219]
**Describe the bug**
`python -m yellowbrick.download` gives a 403 error

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
# Should include imports, dataset loading, and execution
# Add the traceback below
```
Run `python -m yellowbrick.download` from commandline

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?
No

**Expected behavior**
Download should succeed

**Traceback**

```
If applicable, add the traceback from the exception.
```
Traceback (most recent call last):
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\site-packages\yellowbrick\download.py", line 104, in <module>
    download_all(data_home=args.data_home, replace=args.overwrite)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\site-packages\yellowbrick\download.py", line 42, in download_all
    download_data(
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\site-packages\yellowbrick\datasets\download.py", line 95, in download_data
    response = urlopen(url)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\binit_gpu\anaconda3\envs\tf-tensorboard\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Python Version 3.8.12
 - Yellowbrick Version 1.3

**Additional context**
I tried to access to the aws location directly `https://s3.amazonaws.com/ddl-data-lake/yellowbrick/v1.0/bikeshare.zip` and it gave the following error:

```xml
<Error>
<Code>AllAccessDisabled</Code>
<Message>All access to this object has been disabled</Message>
<RequestId>CHRVBWMWCDZABKY4</RequestId>
<HostId>
s8gAjaY5zvE6qXL1I8DEKEPR6Sr42/qzXlmcmv5qTu1tyrpT/LKikrXIMYUuD5TSICH8FtiBsps=
</HostId>
</Error>
```

**Comment by bbengfort** [comment]
@exp-ouroborous thank you for opening such a through bug report! We've recently switched S3 buckets where we were hosting the yellowbrick datasets, please do the following to fix the issue:

```
$ pip install -U yellowbrick
$ python -m yellowbrick.download --cleanup --overwrite
```

This should upgrade your version of Yellowbrick to v1.4, delete any datasets already downloaded and redownload the datasets. Please feel free to reopen the issue if that doesn't work.

See also #1215
