### ISSUE TITLE
Make an Anaconda Package

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#191]
Make an Anacondas package before PyCon to help people get started during the sprints.

**Comment by jkeung** [comment]
I'll take a look at this

**Comment by jkeung** [comment]
https://conda.io/docs/build_tutorials/pkgs.html

**Comment by jkeung** [comment]
Need to make an account on anaconda.org... we should probably make an account and also set the email to be the district data labs email

**Comment by bbengfort** [comment]
Ok, created a DistrictDataLabs account (DDL was taken) -- anyone who needs the password should ask me for it over direct message. 

https://anaconda.org/districtdatalabs

**Comment by jkeung** [comment]
https://anaconda.org/DistrictDataLabs/yellowbrick

```conda install -c districtdatalabs yellowbrick```

**Comment by bbengfort** [comment]
@jkeung Looks great! I think we can close this issue now!

Also it looks like I can add user accounts as collaborators on the DDL org.

**Comment by rebeccabilbro** [comment]
@bbengfort @jkeung I was able to successfully install the conda package on a virtual machine that has Anaconda, but I ran into a [matplotlib issue](https://slack-redir.net/link?url=https%3A%2F%2Fgithub.com%2FContinuumIO%2Fanaconda-issues%2Fissues%2F1068) when trying to import the package:

```
Python 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yellowbrick as yb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.5/site-packages/yellowbrick/__init__.py", line 29, in <module>
    from .style.rcmod import *
  File "/root/anaconda3/lib/python3.5/site-packages/yellowbrick/style/__init__.py", line 21, in <module>
    from .palettes import *
  File "/root/anaconda3/lib/python3.5/site-packages/yellowbrick/style/palettes.py", line 9, in <module>
    import matplotlib.pyplot as plt
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 26, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 20, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 56, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/root/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
ImportError: No module named 'PyQt4'
```

**Comment by bbengfort** [comment]
From Slack: this is a known issue: https://github.com/ContinuumIO/anaconda-issues/issues/1068

I read the entire issue from top to bottom (*whew) and unfortunately I can't see a way that we (yellowbrick developers) can fix the issue by modifying `conda create` somehow. Which would be better. So unfortunately we're going to have to communicate to our users the two fixes:

1. Pin PyQT4 
2. Change the matplotlib backend  

Until Anaconda and Matplotlib development synchronizes. So, can I recommend the following: @rebeccabilbro  can you create a new issue with the error? I will respond with the fixes, then we'll close the issue, and if anyone else has trouble we'll point them to that issue.

**Comment by rebeccabilbro** [comment]
@bbengfort done (see #205). Marking this task complete and closing this card.
