### ISSUE TITLE
Error from KElbowVisualizer's distortion_score method

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#370]
`KElbowVisualizer` is generating a `ValueError` from Sklearn.

### Issue

Using the Yellowbrick `hobbies` corpus and vectorizing with TFIDF, the KElbowVisualizer is generating an error from Sklearn: `ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2`. The `distortion_score` method appears to be causing the error when calling Sklearn's `pairwise_distances` method.

### Code
```
corpus = load_corpus('hobbies')
tfidf  = TfidfVectorizer()
docs   = tfidf.fit_transform(corpus)
visualizer = KElbowVisualizer(KMeans(), k=(4, 8))
visualizer.fit(docs)
visualizer.poof()
```

### Error
```
Traceback (most recent call last):
  File "elbows.py", line 82, in <module>
    visualizer.fit(docs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/cluster/elbow.py", line 245, in fit
    self.scoring_metric(X, self.estimator.labels_)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yellowbrick/cluster/elbow.py", line 87, in distortion_score
    distances = pairwise_distances(instances, [center], metric=metric)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1247, in pairwise_distances
    return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 1090, in _parallel_pairwise
    return func(X, Y, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 223, in euclidean_distances
    X, Y = check_pairwise_arrays(X, Y)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 112, in check_pairwise_arrays
    warn_on_dtype=warn_on_dtype, estimator=estimator)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sklearn/utils/validation.py", line 451, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. check_pairwise_arrays expected <= 2.
```

**Comment by bbengfort** [comment]
I've discovered the source of the problem but not the cause. 

In [`distortion_score`](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/cluster/elbow.py#L84) we take the mean of the instances along `axis=0` to find the centroid. We expect `instances` to be a 2D array, therefore the mean should be a 1D array. In order to pass this to the `pairwise_distances` function, we then covert the center into a single 2D point.

For some reason (still undetermined), in this particular case, the mean is returning a 2D array with only one row in it. It happens that the input is a sparse matrix, not a dense matrix, however, it should still only output a 1D array. Some testing:

```python
import numpy as np 

def amake(ndims=1, s=10, sparse=False):
    cube = [s]*ndims
    return np.random.normal(loc=10.0, scale=1.8, size=cube)

for i in range(1,6):
    mshape = amake(ndims=i).mean(axis=0).ndim 
    print("{}D -> {}D mean".format(i, mshape))
```

output:

```
1D -> 0D mean
2D -> 1D mean
3D -> 2D mean
4D -> 3D mean
5D -> 4D mean
```

So I'm a bit flummoxed, but still looking into it.
