### ISSUE TITLE
Running pip or python in tests directory generates AttributeError: module 'numpy' has no attribute 'core'

### ISSUE THREAD

**Issue by drwaterman** [DistrictDataLabs/yellowbrick#572]
When in the `yellowbrick/tests` directory only (not parent or subdirectories):
Running pip (with arguments or without), or trying to import numpy from the python console, produces the following traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/pip", line 7, in <module>
    from pip._internal import main
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/__init__.py", line 20, in <module>
    from pip._vendor.urllib3.exceptions import DependencyWarning
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 71, in <module>
    import email.parser
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/parser.py", line 12, in <module>
    from email.feedparser import FeedParser, BytesFeedParser
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/feedparser.py", line 27, in <module>
    from email._policybase import compat32
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/_policybase.py", line 9, in <module>
    from email.utils import _has_surrogates
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/utils.py", line 28, in <module>
    import random
  File "/Users/davidwaterman/Documents/yellowbrick/tests/random.py", line 17, in <module>
    import numpy as np
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
AttributeError: module 'numpy' has no attribute 'core'
```

Doing this also creates the file `yellowbrick/tests/__pycache__/random.cpython-36.pyc`. 
Renaming `yellowbrick/tests/random.py` fixes the issue.
Uninstalling and reinstalling pip does not fix.
Cannot recreate on a similar system, appears to be a specific combination of python/pip/numpy/??? versions.

**Desktop:**
 - OS: macOS
 - Python Version: 3.6.1 (vanilla, not Anaconda)
 - Yellowbrick Version: develop brach

**Installed packages:**
```
Package                  Version
------------------------ ---------------
alabaster                0.7.11
atomicwrites             1.1.5
attrs                    18.1.0
Babel                    2.6.0
certifi                  2018.8.13
chardet                  3.0.4
coverage                 4.5.1
cycler                   0.10.0
docutils                 0.14
idna                     2.7
imagesize                1.0.0
Jinja2                   2.10
kiwisolver               1.0.1
MarkupSafe               1.0
matplotlib               2.2.3
mock                     2.0.0
more-itertools           4.3.0
nltk                     3.3
numpy                    1.15.0
numpydoc                 0.8.0
packaging                17.1
pandas                   0.23.4
pbr                      4.2.0
pip                      18.0
pluggy                   0.7.1
py                       1.5.4
pyflakes                 2.0.0
Pygments                 2.2.0
pyparsing                2.2.0
pyspark                  2.1.0+hadoop2.7
pytest                   3.7.2
pytest-cov               2.5.1
pytest-flakes            4.0.0
pytest-spec              1.1.0
python-dateutil          2.7.3
pytz                     2018.5
requests                 2.19.1
scikit-learn             0.19.2
scipy                    1.1.0
setuptools               40.1.0
six                      1.11.0
snowballstemmer          1.2.1
Sphinx                   1.7.7
sphinx-rtd-theme         0.4.1
sphinxcontrib-websupport 1.1.0
urllib3                  1.23
wheel                    0.31.1
```

**Comment by bbengfort** [comment]
Ah, I see what's happening now. The import path looks up the current working directory first, finds the `random.py` module and when they find yellowbrick stuff, they dump. 

You're right though, it seems to be some specific combination, I can't recreate the issue on my system (using pyenv, Pip 10, numpy 1.15, python 3). 

We could change `tests.random` to `tests.rand` -- I wouldn't be particularly bothered by this, especially if it helps prevent confusion when this occurs. My real question is whether or not this would fix the problem or cause a different problem. Would you be willing to test this change out on your system, and repair all of the imports?

**Comment by drwaterman** [comment]
@bbengfort I renamed `tests/random.py` to `tests/ybrandom.py` and changed the import statements in `tests/test_meta.py` and `tests/test_base.py` and everything worked fine.

**Comment by bbengfort** [comment]
@drwaterman ok, though I'd much prefer `rand` over `ybrandom` - would you mind making that quick update? (I don't want someone to think that we're doing some special yellowbrick-specific randomization)

**Comment by drwaterman** [comment]
@bbengfort Yep, I will do that.
