### ISSUE TITLE
data folder not created

### ISSUE THREAD

**Issue by Naba7** [DistrictDataLabs/yellowbrick#722]
As said earlier, python -m yellowbrick.download downloads datasets to yellowbrick/yellowbrick/datasets/fixtures rather not creating data folder in the current directory.The path of download is already set.when i type in the following command 
data = pd.read_csv('data/concrete/concrete.csv')
error occurs
python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandas as pd
>>> data =pd.read_csv('Data/concrete/concrete.csv')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 440, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 787, in __init__
    self._make_engine(self.engine)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1014, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/chad7/anaconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1708, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 384, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 695, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: File b'Data/concrete/concrete.csv' does not exist

As,it says its in here.
chad7@superuser:~/yellowbrick$ python -m yellowbrick.download
Traceback (most recent call last):
  File "/home/chad7/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chad7/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chad7/yellowbrick/yellowbrick/download.py", line 94, in <module>
    download_all(data_home=args.data_home, replace=args.overwrite)
  File "/home/chad7/yellowbrick/yellowbrick/download.py", line 43, in download_all
    meta['url'], meta['signature'], data_home=data_home, replace=replace
  File "/home/chad7/yellowbrick/yellowbrick/datasets/download.py", line 88, in download_data
    ).format(archive))
yellowbrick.exceptions.DatasetsError: dataset already exists at /home/chad7/yellowbrick/yellowbrick/datasets/fixtures/bikeshare.zip, set replace=False to overwrite

**Comment by pdamodaran** [comment]
Hi @Naba7 - just wanted to follow up with you to see if you are still having any issues with downloading the datasets.

**Comment by bbengfort** [comment]
Hi @Naba7 based on our other conversations I believe this was resolved, so I'm going to go ahead and close this issue. Thank you for contributing to Yellowbrick!

**Comment by Naba7** [comment]
Thanks @pdamodaran and @bbengfort for helping

**Comment by Naba7** [comment]
I want to clear everyone on this . The actual statement is python -m yellow
brick.download ./data rather than python -m yellow brick.downloads ./data
