### ISSUE TITLE
AppVeyor with Conda/Miniconda Broken

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#744]
AppVeyor is failing on the Miniconda3 matrix when installing NLTK:

```
python -m nltk.downloader popular
Traceback (most recent call last):
  File "C:\Miniconda3-x64\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Miniconda3-x64\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Miniconda3-x64\lib\site-packages\nltk\__init__.py", line 152, in <module>
    from nltk.stem import *
  File "C:\Miniconda3-x64\lib\site-packages\nltk\stem\__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "C:\Miniconda3-x64\lib\site-packages\nltk\stem\snowball.py", line 32, in <module>
    from nltk.corpus import stopwords
  File "C:\Miniconda3-x64\lib\site-packages\nltk\corpus\__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "C:\Miniconda3-x64\lib\site-packages\nltk\corpus\reader\__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "C:\Miniconda3-x64\lib\site-packages\nltk\corpus\reader\panlex_lite.py", line 15, in <module>
    import sqlite3
  File "C:\Miniconda3-x64\lib\sqlite3\__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "C:\Miniconda3-x64\lib\sqlite3\dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: DLL load failed: The specified module could not be found.
```

See: https://help.appveyor.com/discussions/problems/20308-importerror-dll-load-failed-the-specified-module-could-not-be-found for more details and discussion.

**Comment by bbengfort** [comment]
This issue is occurring again, this time with the `Previous Visual Studio 2017` image.

**Comment by bbengfort** [comment]
Reverting to the default image, Visual Studio 2017, did not work the error still occurs.

Build:
https://ci.appveyor.com/project/districtdatalabs/yellowbrick/builds/23948948/job/9dct318qikbot98h

**Comment by bbengfort** [comment]
Even more bad news, the previous solution, reverting to Previous Visual Studio 2017 also did not work.

Build:
https://ci.appveyor.com/project/districtdatalabs/yellowbrick/builds/23949638

**Comment by JaimieMurdock** [comment]
Having the same issue in another project :/

**Comment by bbengfort** [comment]
@JaimieMurdock sorry to hear that - which project? 

Perhaps if you post a comment on the [issue we opened on AppVeyor](https://help.appveyor.com/discussions/problems/20308-importerror-dll-load-failed-the-specified-module-could-not-be-found) -- it will help alert them more to the problem? Their previous solution, revert to the "Previous Visual Studio 2015" image is now also broken, and unfortunately there is nothing we can do until they sort it out.

**Comment by rebeccabilbro** [comment]
Unfortunately it looks like this problem has [come back](https://ci.appveyor.com/project/districtdatalabs/yellowbrick/builds/34684452/job/3e5pbqfokxmb0fj8#L223).

**Comment by bbengfort** [comment]
Now that we've moved off of AppVeyor to GitHub Actions, I'm closing this issue.
