### ISSUE TITLE
ImportError: cannot import name 'calinski_harabasz_score' with sklearn 0.20.2

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#902]
**Describe the bug**

After #887 we unintentionally injected an `ImportError` for our current set of dependencies; namely `calinski_harabasz_score` doesn't exist in scikitlearn 0.20. This does not show up in our current CI/test suite because we always install the latest deps. There are two options to fix:

1. Update our `requirements.txt` to a later version of scikit-learn
2. Wrap the import in `try/except`, e.g.

```python
try:
    from sklearn.metrics import calinski_harabasz_score
except ImportError:
    from sklearn.metrics import calinski_harabaz_score
```

**To Reproduce**

```
>>> from yellowbrick.cluster import ElbowVisualizer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/benjamin/Workspace/git/yellowbrick/yellowbrick/cluster/__init__.py", line 23, in <module>
    from .elbow import *
  File "/Users/benjamin/Workspace/git/yellowbrick/yellowbrick/cluster/elbow.py", line 33, in <module>
    from sklearn.metrics import calinski_harabasz_score
ImportError: cannot import name 'calinski_harabasz_score'
```

**Expected behavior**

If we use the minimum dependencies as set in `requirements.txt` we should not have import errors. 

**Traceback**

From the tests:

```
________________________________ ERROR collecting tests/test_cluster/test_silhouette.py ________________________________
ImportError while importing test module '/Users/benjamin/Workspace/git/yellowbrick/tests/test_cluster/test_silhouette.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_cluster/test_silhouette.py:30: in <module>
    from yellowbrick.cluster.silhouette import SilhouetteVisualizer
yellowbrick/cluster/__init__.py:23: in <module>
    from .elbow import *
yellowbrick/cluster/elbow.py:33: in <module>
    from sklearn.metrics import calinski_harabasz_score
E   ImportError: cannot import name 'calinski_harabasz_score'
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version: 3.6.2
 - Yellowbrick Version: develop
- Scikit-Learn Version: 0.20.2

**Comment by bbengfort** [comment]
Another question is whether or not we should add different versions of scikit-learn to our test matrix on CI to make sure we catch stuff like this.
