### ISSUE TITLE
KElbow raises confusing `ValueError` when optimal k is outside provided k-range

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#943]
**Describe the bug**
We seem to have a bug in our updated `KElbow` visualizer following the updates in #813 and #935. When the `locate_elbow` param is set to `True` (which it is by default), we get a `ValueError` when calling `fit` on the visualizer.

**To Reproduce**

```python
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from yellowbrick.cluster import KElbowVisualizer
X, y = make_blobs(centers=12, n_samples=1000, n_features=16, shuffle=True)
viz = KElbowVisualizer(KMeans(), k=(4,12))
viz.fit(X)
```
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rbilbro/pyjects/my_yb/yellowbrick/cluster/elbow.py", line 334, in fit
    self.k_values_, self.k_scores_, **locator_kwargs
  File "/Users/rbilbro/pyjects/my_yb/yellowbrick/utils/kneed.py", line 126, in __init__
    self.knee, self.norm_knee = min(self.all_knees), min(self.all_norm_knees)
ValueError: min() arg is an empty sequence
```

**Dataset**
`make_blobs`

**Expected behavior**
`fit` should fit the `KElbow` visualizer without raising an error.

**Desktop (please complete the following information):**
 - OS: macOS
 - Python Version 3.7
 - Yellowbrick Version v1.0 dev

**Comment by rebeccabilbro** [comment]
After digging into this a bit more, it looks like the bug occurs when the number of `centers` in the dataset is smaller than the `k` range provided to the `KElbowVisualizer`, so:

```python
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from yellowbrick.cluster import KElbowVisualizer
X, y = make_blobs(centers=12, n_samples=1000, n_features=16, centers=8, shuffle=True)
viz = KElbowVisualizer(KMeans(), k=(4,12))
viz.fit(X)
```

is ok (since 4<=8<=12)

but ...

```python
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from yellowbrick.cluster import KElbowVisualizer
X, y = make_blobs(centers=12, n_samples=1000, n_features=16, centers=8, shuffle=True)
viz = KElbowVisualizer(KMeans(), k=(10,12))
viz.fit(X)
```

... causes the `ValueError` behavior.

Also, *not* setting a `centers` parameter (as in the initial example shown in this bug report) also causes the error because `centers` is `None` by default.
