### ISSUE TITLE
Python3.5 Syntax Error on import

### ISSUE THREAD

**Issue by Ashton-Sidhu** [DistrictDataLabs/yellowbrick#976]
**Describe the bug**
A ',' after **kwargs argument causing incompatibility issues with python3.5.

Is yellowbrick supporting v3.5 of python or has it moved to just supporting python 3.6+ as the build testing suggests?

If yellowbrick continues to support 3.5 I can submit a PR that fixes this issue.

Thanks!

**To Reproduce**

```python
import yellowbrick
```

**Traceback**

``` Traceback (most recent call last):

  File "/usr/local/lib/python3.5/unittest/loader.py", line 462, in _find_test_path

    package = self._get_module_from_name(name)

  File "/usr/local/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name

    __import__(name)

  File "/home/circleci/project/pyautoml/__init__.py", line 9, in <module>

    from .modelling import Model

  File "/home/circleci/project/pyautoml/modelling/__init__.py", line 1, in <module>

    from .model import Model

  File "/home/circleci/project/pyautoml/modelling/model.py", line 14, in <module>

    from pyautoml.modelling.util import (_get_cv_type, _run_models_parallel,

  File "/home/circleci/project/pyautoml/modelling/util.py", line 8, in <module>

    from yellowbrick.model_selection import CVScores, LearningCurve

  File "/home/circleci/project/venv/lib/python3.5/site-packages/yellowbrick/__init__.py", line 39, in <module>

    from .classifier import ROCAUC, ClassBalance, ClassificationScoreVisualizer

  File "/home/circleci/project/venv/lib/python3.5/site-packages/yellowbrick/classifier/__init__.py", line 25, in <module>

    from .base import ClassificationScoreVisualizer

  File "/home/circleci/project/venv/lib/python3.5/site-packages/yellowbrick/classifier/base.py", line 118

    **kwargs,

SyntaxError: invalid syntax
```

**Desktop (please complete the following information):**
 - OS: WSL
 - Python Version 3.5
 - Yellowbrick Version 1.0.post1

**Comment by bbengfort** [comment]
@Ashton-Sidhu thank you for the bug report, this is fixed in 49d470 -- and should be released in the v1.0.1 hotfix shortly. Let me know if you have any further issues!
